PackageSources = Base.m Braids.m TubePlot.m DrawPD.m Data.m \
	BraidData.m GaussCode.m GC2PD.m Indiana.m HOMFLYPT.m Kauffman.m \
	Kh.m MorseLink.m DrawMorseLink.m ML2PD.m AlexanderConway.m \
	VogelsAlgorithm.m MultivariableAlexander.m REngine.m TestRMatrix.m \
	CJREngine.m ColouredJones.m

init.m
