src = /home/KnotTheory/KnotTheory/
PackageSources = $(src)/Base.m $(src)/Braids.m $(src)/TubePlot.m \
	$(src)/DrawPD.m $(src)/Data.m $(src)/BraidData.m $(src)/GaussCode.m \
	$(src)/GC2PD.m $(src)/Indiana.m $(src)/HOMFLYPT.m \
	$(src)/Kauffman.m $(src)/Kh.m $(src)/MorseLink.m
	$(src)/DrawMorseLink.m $(src)/ML2PD.m $(src)/AlexanderConway.m
	$(src)/VogelsAlgorithm.m $(src)/MultivariableAlexander.m
	$(src)/REngine.m $(src)/TestRMatrix.m \
	$(src)/CJREngine.m $(src)/ColouredJones.m
