(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





BeginPackage[
    "KnotTheory`QuantumKnotInvariants`",{"KnotTheory`","QuantumGroups`","QuantumGroups`Braiding`",
      "QuantumGroups`Utilities`DataPackage`"}];

QuantumKnotInvariant::about="Quantum knot invariants are calculated using the mathematica package QuantumGroups`, written by Scott Morrison 2003-2008.";

QuantumKnotInvariant::usage="QuantumKnotInvariant[\[CapitalGamma], V][K][q] calculates the quantum knot invariant of the knot K in the representation V of the quantum group \[CapitalGamma]. This relies on the QuantumGroups` package, and you should look there for details of how \[CapitalGamma] and V may be specified.

Examples:
   QuantumKnotInvariant[Subscript[A,2], Irrep[Subscript[A,2]][{1, 0}]][Knot[5, 2]][q]
   QuantumKnotInvariant[Subscript[G,2], Irrep[Subscript[G,2]][{1, 0}]\[CirclePlus]Irrep[Subscript[G,2]][{0, 1}]][Knot[5, 2]][q]"

PackageQuantumKnotInvariants::usage=
  "PackageQuantumKnotInvariants[\[CapitalGamma]] saves all calculated quantum knot invariants for the quantum group K into a data file in the QuantumGroupsDataDirectory[]."

Begin["`Private`"]

q=Global`q;

Wants[x_]:=
  (Off[Get::noopen];Off[Needs::nocont];Needs[x];On[Needs::nocont];
    On[Get::noopen];)

ExtractMatrices[indices:{__Integer},matrices_]:=
  Extract[matrices,
    indices/.{n_/;n<0\[RuleDelayed]{2,-n},n_/;n>0\[RuleDelayed]{1,n}}]

TogetherDot[x_,y_]:=x.y
TogetherDot[x_,y_,z__]:=TogetherDot[Together[x.y],z]

\!\(\(QuantumKnotInvariant[\[CapitalGamma]_\_n_, V_]\)[K_] := \(\(QuantumKnotInvariant[\[CapitalGamma]\_n, V]\)[K] = Module[{br = BR[K], k, data}, \[IndentingNewLine]CreditMessage[QuantumKnotInvariant::about]; \[IndentingNewLine]Wants["\<QuantumGroups`Data`\>" <> ToString[\[CapitalGamma]] <> ToString[n] <> "\<`BraidingData`\>"]; \[IndentingNewLine]k = br\[LeftDoubleBracket]1\[RightDoubleBracket]; \[IndentingNewLine]data = \(BraidingData[\[CapitalGamma]\_n]\)[V, k]; \[IndentingNewLine]Function[{Global`q0}, Evaluate[Expand[Together[Plus @@ \(\((#\[LeftDoubleBracket]1\[RightDoubleBracket] Tr[TogetherDot @@ ExtractMatrices[br\[LeftDoubleBracket]2\[RightDoubleBracket], #\[LeftDoubleBracket]2\[RightDoubleBracket]]] &)\) /@ data\)]] /. q \[Rule] Global`q0]]\[IndentingNewLine]]\)\)

\!\(PackageQuantumKnotInvariants[\[CapitalGamma]_\_n_] := PackageData[\[IndentingNewLine]{{QuantumKnotInvariant, HoldPattern[\(QuantumKnotInvariant[\[CapitalGamma]\_n, _]\)[_Knot]]}}, \[IndentingNewLine]{ToString[\[CapitalGamma]] <> ToString[n], "\<QuantumKnotInvariants\>"}, \[IndentingNewLine]"\<Needs\>" \[Rule] {"\<QuantumGroups`\>", "\<KnotTheory`\>", "\<KnotTheory`QuantumKnotInvariants`\>"}, \[IndentingNewLine]"\<ExtraPrivateCode\>" \[Rule] "\<q0=Global`q0;\>", "\<UseGzip\>" \[Rule] False\[IndentingNewLine]]\)

End[]

EndPackage[]